### ISSUE TITLE
Bug: Update tasks (create dirs) to the following format

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#224]
```
- name: Create required directories.
  file:
    path: "{{ volumes_root }}/{{ item }}"
    state: directory
    owner: "{{ uid_output.stdout }}"
    group: "{{ gid_output.stdout }}"
  loop:
    - portus
    - portus/secrets
    - portus/mariadb
    - portus/registry
    - portus/registry/data
    - portus/clair
  become: yes
```
