### ISSUE TITLE
Bug: Task Stop services not working

### ISSUE THREAD

**Issue by denis-ev** [VivumLab/VivumLab#259]
**Describe the bug**
```
TASK [Stop services] ********************************************************************************************************************************************
skipping: [myserver] => (item=portus) 
```

**To Reproduce**
```
---
- hosts: all
  gather_facts: no
  tags: setup

  tasks:
    - name: Stop services
      systemd:
        name: "{{ service_item }}"
        state: stopped
      when: query | bool
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      vars:
        query: "{{ service_item + '.enable' }}"
      become: yes
```
changing this back to 
```
---
- hosts: all
  gather_facts: no
  tags: setup

  tasks:
    - name: Stop services
      systemd:
        name: "{{ service_item }}"
        state: stopped
      when: query
      loop: "{{ services | flatten(1) }}"
      loop_control:
        loop_var: service_item
      vars:
        query: "{{ service_item + '.enable' }}"
      become: yes
```
makes it work, but shows a deprecation warning that this won't work anymore soon.

**Additional context**
